name: untitled
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #camera: ^0.10.5+5
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1
  image_picker: ^0.8.6
  collection: ^1.16.0
  image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 # cloud_firestore: ^4.10.0
 # firebase_auth: ^4.11.0
 # firebase_core: ^2.18.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5

  cloud_firestore: 4.9.2
  firebase_core: 2.16.0
  firebase_storage: 11.2.7
  firebase_auth: 4.10.0
  firebase_messaging: 14.6.8
  firebase_analytics: 10.5.0

  camera_deep_ar: ^0.0.2+3
  #image_picker: ^1.0.4
  #flutter_launcher_icons: ^0.13.1

  #cupertino_icons: ^1.0.6



flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/app_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/image/app_logo_foreground.png"


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/ar/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
