// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP1fatav202cNyqTKiAKZwm5-PhEuKlkg',
    appId: '1:879929698551:web:aa05f99c4309c9b2594bf2',
    messagingSenderId: '879929698551',
    projectId: 'untitlec-9bb05',
    authDomain: 'untitlec-9bb05.firebaseapp.com',
    storageBucket: 'untitlec-9bb05.appspot.com',
    measurementId: 'G-X84HKFVWJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDetntmKvuY12mmW6C5qyYpK3oEzUsr118',
    appId: '1:879929698551:android:24534c086e4b546b594bf2',
    messagingSenderId: '879929698551',
    projectId: 'untitlec-9bb05',
    storageBucket: 'untitlec-9bb05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVyiNnsSpfKcLm68HJ_HnSN21o0zPitzA',
    appId: '1:879929698551:ios:de26d4e6bbcc8a51594bf2',
    messagingSenderId: '879929698551',
    projectId: 'untitlec-9bb05',
    storageBucket: 'untitlec-9bb05.appspot.com',
    iosClientId: '879929698551-f9gop327u54m0lf2peqcvqm4k41hqsvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.arglassesproja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVyiNnsSpfKcLm68HJ_HnSN21o0zPitzA',
    appId: '1:879929698551:ios:9fe24af4a102405b594bf2',
    messagingSenderId: '879929698551',
    projectId: 'untitlec-9bb05',
    storageBucket: 'untitlec-9bb05.appspot.com',
    iosClientId: '879929698551-lplt9rthr3098b3ndumamrend0r1ts53.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
